priority_clubs:
  - SL Benfica
  - Sporting CP
  - FC Porto
  - SC Braga
  - FC Famalicão
  - Vitória Guimarães SC
  - GD Estoril Praia
  - Rio Ave FC
  - Gil Vicente FC
  - Casa Pia AC
  - FC Arouca
  - Moreirense FC

